const FooterHome = () => {
    const year = new Date().getFullYear();

    return (
        <>
            <footer className="mt-6 rounded-[2rem] border border-border/60 bg-card px-5 py-10 sm:px-8 sm:py-12 lg:px-12">
                <div className="mx-auto max-w-7xl">
                    <div className="flex flex-col gap-6 border-b border-border/60 pb-8 lg:flex-row lg:items-end lg:justify-between">
                        <div className="max-w-2xl">
                            <p className="caps-sm text-sm font-semibold uppercase text-lime-400">Codeyen AI</p>
                            <h2 className="mt-4 font-serif text-3xl leading-tight tracking-tight text-foreground sm:text-4xl">
                                Intuitive, conversational, and powerfully simple AI web development.
                            </h2>
                            <p className="mt-4 text-sm leading-7 text-muted-foreground sm:text-base">
                                Generate beautiful, functional websites from simple text prompts, keeping your creative intent at the center of the entire process.
                            </p>
                        </div>

                        <div className="flex flex-col gap-3 sm:flex-row">
                        </div>
                    </div>

                    <div className="pt-8">
                        <div>
                            <p className="text-sm font-semibold text-foreground">About</p>
                            <p className="mt-4 text-sm leading-7 text-muted-foreground">
                                Codeyen is an AI-first company dedicated to democratizing web development. We're passionate about removing technical barriers and making web creation accessible to everyone. Our platform uses conversational AI to turn simple text prompts into powerful, production-ready websites, allowing our users to focus on their ideas, not the code.
                            </p>
                        </div>
                    </div>

                    <div className="mt-8 flex flex-col gap-3 border-t border-border/60 pt-6 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between">
                        <p>&copy; {year} Codeyen AI</p>
                        <p>Generated by AI. Guided by you.</p>
                    </div>
                </div>
            </footer>
        </>
    )
}

export default FooterHome;